package dev.sealbreaker.core.gametest;

import net.neoforged.bus.api.IEventBus;
import net.neoforged.fml.common.Mod;

/**
 * The test-only mod that carries {@code sb_core}'s game tests. Lives in the {@code gametest} source set, is
 * loaded by the {@code gameTestServer} run alone and never reaches the shipped jar. Test instances are the
 * JSON files under {@code data/sb_core_tests/test_instance/}; the arena template they share is
 * {@code data/sb_core_tests/structure/arena.nbt} (generated by {@code tools/gen_structures.py}).
 */
@Mod(SbCoreTests.MOD_ID)
public final class SbCoreTests {
    public static final String MOD_ID = "sb_core_tests";

    public SbCoreTests(IEventBus modEventBus) {
        SbCoreTestFunctions.register(modEventBus);
    }
}
